services:
  api:
    image: phamdongchinh683/backend-fastify:latest
    container_name: api
    restart: always
    mem_limit: 256m
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - internal-net
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    mem_limit: 768m
    env_file:
      - .env
    environment:
      POSTGRES_DB: busgo
      POSTGRES_USER: busgo
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal-net
    ports:
      - "5433:5432"
volumes:
  db_data:

networks:
  internal-net:
    driver: bridge
