services:
  chat-ai-api1:
    image: phamdongchinh683/busgo-api:${IMAGE_TAG:-latest}
    container_name: chat-ai-api1
    labels:
      - "app=busgo-chat-ai"
    restart: unless-stopped
    mem_limit: 512m
    env_file:
      - .env
    environment:
      API_SERVICE: ${API_SERVICE:-chat-ai}
    ports:
      - "127.0.0.1:3011:3000"
    volumes:
      - chat_ai_storage:/app/storage
    networks:
      - internal-net

  chat-ai-api2:
    image: phamdongchinh683/busgo-api:${IMAGE_TAG:-latest}
    container_name: chat-ai-api2
    labels:
      - "app=busgo-chat-ai"
    restart: unless-stopped
    mem_limit: 512m
    env_file:
      - .env
    environment:
      API_SERVICE: ${API_SERVICE:-chat-ai}
    ports:
      - "127.0.0.1:3012:3000"
    volumes:
      - chat_ai_storage:/app/storage
    networks:
      - internal-net

volumes:
  chat_ai_storage:

networks:
  internal-net:
    driver: bridge
