services:
  api:
    image: phamdongchinh683/busgo-api:${IMAGE_TAG:-latest}
    container_name: api
    restart: always
    mem_limit: 512m
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - internal-net
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    mem_limit: 768m
    environment:
      POSTGRES_DB: busgo
      POSTGRES_USER: busgo
      POSTGRES_PASSWORD: Chinh123021312412
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal-net
    ports:
      - "5433:5432"
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - "127.0.0.1:3006:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    restart: always
    pid: host
    network_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db_data:
  netdata_config:
  netdata_lib:
  netdata_cache:


networks:
  internal-net:
    driver: bridge
