name: BusGo API CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Production Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/busgo-api:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/busgo-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Jenkins Deployment
        run: |
          CRUMB=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            "${{ secrets.JENKINS_URL }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")

          curl -X POST -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
            -H "$CRUMB" \
            "${{ secrets.JENKINS_URL }}/job/busgo-api/buildWithParameters?IMAGE_TAG=${{ github.sha }}"

